# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import ui_controller_service_pb2 as ui__controller__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ui_controller_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UiControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.showExtendedControls = channel.unary_unary(
                '/android.emulation.control.UiController/showExtendedControls',
                request_serializer=ui__controller__service__pb2.PaneEntry.SerializeToString,
                response_deserializer=ui__controller__service__pb2.ExtendedControlsStatus.FromString,
                _registered_method=True)
        self.closeExtendedControls = channel.unary_unary(
                '/android.emulation.control.UiController/closeExtendedControls',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ui__controller__service__pb2.ExtendedControlsStatus.FromString,
                _registered_method=True)
        self.setUiTheme = channel.unary_unary(
                '/android.emulation.control.UiController/setUiTheme',
                request_serializer=ui__controller__service__pb2.ThemingStyle.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getUserConfig = channel.unary_unary(
                '/android.emulation.control.UiController/getUserConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ui__controller__service__pb2.UserConfig.FromString,
                _registered_method=True)


class UiControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def showExtendedControls(self, request, context):
        """PaneEntry specifies which pane will be selected when
        the extended control is shown. If the extended is visible already,
        this method will set visibilityChangedto to false.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeExtendedControls(self, request, context):
        """this method has no effect if the extended controls are hidden.
        In that case, visibilityChanged will be set to false;
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setUiTheme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUserConfig(self, request, context):
        """Returns the user configuration of the running emulator. The user
        configuration contains information about the user interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UiControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'showExtendedControls': grpc.unary_unary_rpc_method_handler(
                    servicer.showExtendedControls,
                    request_deserializer=ui__controller__service__pb2.PaneEntry.FromString,
                    response_serializer=ui__controller__service__pb2.ExtendedControlsStatus.SerializeToString,
            ),
            'closeExtendedControls': grpc.unary_unary_rpc_method_handler(
                    servicer.closeExtendedControls,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ui__controller__service__pb2.ExtendedControlsStatus.SerializeToString,
            ),
            'setUiTheme': grpc.unary_unary_rpc_method_handler(
                    servicer.setUiTheme,
                    request_deserializer=ui__controller__service__pb2.ThemingStyle.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getUserConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.getUserConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ui__controller__service__pb2.UserConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'android.emulation.control.UiController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('android.emulation.control.UiController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UiController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def showExtendedControls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.UiController/showExtendedControls',
            ui__controller__service__pb2.PaneEntry.SerializeToString,
            ui__controller__service__pb2.ExtendedControlsStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def closeExtendedControls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.UiController/closeExtendedControls',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ui__controller__service__pb2.ExtendedControlsStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setUiTheme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.UiController/setUiTheme',
            ui__controller__service__pb2.ThemingStyle.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUserConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.UiController/getUserConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ui__controller__service__pb2.UserConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
